import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  variable: "--font-geist-sans",
  src: "../public/fonts/Geist[wght].ttf",
});

const geistMono = localFont({
  variable: "--font-geist-mono",
  src: "../public/fonts/GeistMono[wght].ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-[70ch] m-2.5`}
      >
        {children}
      </body>
    </html>
  );
}
