import Head from 'next/head'
import { PostPreview } from '../components/molecules/PostPreview'
import { Post } from '../types'
import { getAllPosts } from '../utils/mdx'

type HomeProps = {
  posts: Post[]
}

const Home = ({ posts }: HomeProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-xl md:text-2xl lg:text-3xl mt-16">
        <span className="font-medium">Howdy there.</span> Find out what
        we&apos;re thinking about with a look behind the curtain at the things
        that make us tick.
      </h1>

      <ul className="mt-14">
        {posts.map((post, i) => (
          <li key={i} className={i === 0 ? '' : 'mt-9'}>
            <PostPreview
              date={post.date}
              title={post.frontmatter.title}
              previewText={post.frontmatter.description}
              postSlug={post.slug}
            />
          </li>
        ))}
      </ul>
    </>
  )
}

export const getStaticProps = async () => {
  const posts = await getAllPosts()
  return {
    props: {
      posts,
    },
  }
}

export default Home
