import Head from 'next/head'
import Link from 'next/link'
import { Post } from '../types'
import { getAllPosts } from '../utils/mdx'
import styles from '../styles/Home.module.css'
import { Header } from '../components/molecules/Header'

type HomeProps = {
  posts: Post[]
}

const Home = ({ posts }: HomeProps) => {
  return (
    <div className="mt-9 mx-4 sm:mt-16 sm:mx-8 md:mt-32 md:mx-20">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-5xl mx-auto">
        <Header />
        <main>
          <ul>
            {posts.map((post, i) => (
              <li key={i}>
                <Link href={`/posts/${post.slug}`}>
                  <a className="underline text-blue-500">
                    {post.frontmatter.title}
                  </a>
                </Link>
              </li>
            ))}
          </ul>
        </main>
      </div>
    </div>
  )
}

export const getStaticProps = async () => {
  const posts = await getAllPosts()
  return {
    props: {
      posts,
    },
  }
}

export default Home
